# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  android_prebuilts_clang_kernel_linux-x86_clang-r416183b = {
    pname = "android_prebuilts_clang_kernel_linux-x86_clang-r416183b";
    version = "54220fd601050b350b2af7adc913089ebf0e7aed";
    src = fetchFromGitHub {
      owner = "LineageOS";
      repo = "android_prebuilts_clang_kernel_linux-x86_clang-r416183b";
      rev = "54220fd601050b350b2af7adc913089ebf0e7aed";
      fetchSubmodules = false;
      sha256 = "sha256-o9e5VRR6s2T9NDwDY8XuG2GYUKbZQF1s687gPlE0+RY=";
    };
    date = "2022-11-01";
  };
  anykernel-kernelsu = {
    pname = "anykernel-kernelsu";
    version = "ee30bad85a483cad2b1e4ff34e69f983a04f875a";
    src = fetchFromGitHub {
      owner = "Kernel-SU";
      repo = "AnyKernel3";
      rev = "ee30bad85a483cad2b1e4ff34e69f983a04f875a";
      fetchSubmodules = false;
      sha256 = "sha256-QJS4+1teNcgUOy2gD+KuoEG/9pUNd/6uSH84AkAlVoQ=";
    };
    date = "2023-10-30";
  };
  anykernel-osm0sis = {
    pname = "anykernel-osm0sis";
    version = "db90e19aae369c9c10b956a08003cee3958d50a0";
    src = fetchFromGitHub {
      owner = "osm0sis";
      repo = "AnyKernel3";
      rev = "db90e19aae369c9c10b956a08003cee3958d50a0";
      fetchSubmodules = false;
      sha256 = "sha256-MofvAxGUB4kcOmm42u3rDFPR7Pj63OjaC4FRP9jAy0k=";
    };
    date = "2024-12-17";
  };
  gcc-aarch64-linux-android = {
    pname = "gcc-aarch64-linux-android";
    version = "5797d7f622321e734558bd3372a9ab5ad6e6a48e";
    src = fetchFromGitHub {
      owner = "kindle4jerry";
      repo = "aarch64-linux-android-4.9-bakup";
      rev = "5797d7f622321e734558bd3372a9ab5ad6e6a48e";
      fetchSubmodules = false;
      sha256 = "sha256-ZrQmFyiDOKg+qcgdpZqtz+LgDDaao2W27kdZZ2As8XU=";
    };
    date = "2020-02-22";
  };
  gcc-arm-linux-androideabi = {
    pname = "gcc-arm-linux-androideabi";
    version = "3ecb542702c2ca0e502533c3f6d02f0f06f584f1";
    src = fetchFromGitHub {
      owner = "KudProject";
      repo = "arm-linux-androideabi-4.9";
      rev = "3ecb542702c2ca0e502533c3f6d02f0f06f584f1";
      fetchSubmodules = false;
      sha256 = "sha256-5aF2Pl+h6J8/5TfQf2ojp3FCnoKakWH6KBCkWdy5ho8=";
    };
    date = "2019-11-25";
  };
  kernelsu-next = {
    pname = "kernelsu-next";
    version = "v1.0.5";
    src = fetchgit {
      url = "https://github.com/rifsxd/KernelSU-Next.git";
      rev = "v1.0.5";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-XAsZH9NJX4WaKico03T542JZsbL4Gdb5WuURWg6VIRQ=";
    };
  };
  kernelsu-next-revision-code = {
    pname = "kernelsu-next-revision-code";
    version = "12430";
    src = fetchurl {
      url = "https://example.com";
      sha256 = "sha256-6o+sfGX7WJsNU1YPUlH3T56bJDR43Laz6nm142RJyNk=";
    };
  };
  kernelsu-stable = {
    pname = "kernelsu-stable";
    version = "v0.9.5";
    src = fetchgit {
      url = "https://github.com/tiann/KernelSU.git";
      rev = "v0.9.5";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-pvaL6KEB7X3s8zyLQSPhBhoXaNdVDthH7HnAZRE9JYk=";
    };
  };
  kernelsu-stable-revision-code = {
    pname = "kernelsu-stable-revision-code";
    version = "11872";
    src = fetchurl {
      url = "https://example.com";
      sha256 = "sha256-6o+sfGX7WJsNU1YPUlH3T56bJDR43Laz6nm142RJyNk=";
    };
  };
  lineage-nightly-pstar_bootImg = {
    pname = "lineage-nightly-pstar_bootImg";
    version = "20250310";
    src = fetchurl {
      url = "https://mirrorbits.lineageos.org/full/pstar/20250310/boot.img";
      sha256 = "sha256-fEr0vY7F8C4MX3R5g5dsY/xX/2ic6fyYZgPCvImY5MU=";
    };
  };
  linux-amazon-karnak = {
    pname = "linux-amazon-karnak";
    version = "e22c713c7c4f0c8d08267f6bba98b8c4cde8310f";
    src = fetchFromGitHub {
      owner = "mt8163";
      repo = "android_kernel_amazon_karnak_4.9";
      rev = "e22c713c7c4f0c8d08267f6bba98b8c4cde8310f";
      fetchSubmodules = false;
      sha256 = "sha256-viqlQBPd2SuiAphFKiwjtckC3gDTGkbLv2dgZKMP3Oc=";
    };
    date = "2023-10-09";
  };
  linux-moto-pstar-lineageos-22_1 = {
    pname = "linux-moto-pstar-lineageos-22_1";
    version = "85e6c6ea3adf04eafca566152bfc71d6b27eed9c";
    src = fetchFromGitHub {
      owner = "AndroidAppsUsedByMyself";
      repo = "android_kernel_motorola_sm8250";
      rev = "85e6c6ea3adf04eafca566152bfc71d6b27eed9c";
      fetchSubmodules = false;
      sha256 = "sha256-VoeazEybEyKbswiQayfXdIZsT3YENHUhRumfJ4/Y95Q=";
    };
    date = "2025-02-18";
  };
  linux-moto-rtwo-lineageos-21 = {
    pname = "linux-moto-rtwo-lineageos-21";
    version = "1bdeb4f5c8d2b98ef5f2bedaa5d704032dffd676";
    src = fetchFromGitHub {
      owner = "LineageOS";
      repo = "android_kernel_motorola_sm8550";
      rev = "1bdeb4f5c8d2b98ef5f2bedaa5d704032dffd676";
      fetchSubmodules = false;
      sha256 = "sha256-ZK/DH5N5LdkLe48cANESjw1x74aXoZLFoMAwEDvzEk4=";
    };
    date = "2024-12-21";
  };
  linux-moto-rtwo-lineageos-22_1 = {
    pname = "linux-moto-rtwo-lineageos-22_1";
    version = "f31482b33068951d3a29bade94c0eecebeb558b3";
    src = fetchFromGitHub {
      owner = "LineageOS";
      repo = "android_kernel_motorola_sm8550";
      rev = "f31482b33068951d3a29bade94c0eecebeb558b3";
      fetchSubmodules = false;
      sha256 = "sha256-HayzpNIWja4rnpE7xhDKF6cgZAqK6osZvbUTVarPMDk=";
    };
    date = "2025-03-02";
  };
  linux-oneplus-8t-blu-spark = {
    pname = "linux-oneplus-8t-blu-spark";
    version = "64c109e3f3ba97fa7aed730ab7b4238b91df028b";
    src = fetchFromGitHub {
      owner = "engstk";
      repo = "op8";
      rev = "64c109e3f3ba97fa7aed730ab7b4238b91df028b";
      fetchSubmodules = false;
      sha256 = "sha256-KWLtY7KWhHmk6LVYpvIz6XT93+yjteex/250crk9Lxw=";
    };
    date = "2024-12-26";
  };
  los-pstar-kernel-patches = {
    pname = "los-pstar-kernel-patches";
    version = "508f67fb6c474ade86b66e02a1f0f818ea8f9d92";
    src = fetchFromGitHub {
      owner = "AndroidAppsUsedByMyself";
      repo = "kernel_patches";
      rev = "508f67fb6c474ade86b66e02a1f0f818ea8f9d92";
      fetchSubmodules = false;
      sha256 = "sha256-qdW7+4nq5kqGSlTFEMsDlmfnxqakR0yzMtvOlBtdxk0=";
    };
    date = "2025-02-09";
  };
  susfs-android13-5_15 = {
    pname = "susfs-android13-5_15";
    version = "eeb4737559da1321d0f121f1b3aa75ae9567075a";
    src = fetchgit {
      url = "https://gitlab.com/simonpunk/susfs4ksu.git";
      rev = "eeb4737559da1321d0f121f1b3aa75ae9567075a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-rWXdmb2vt7V6stfSb2+NoYUgtkc7cC3eyZcw9E9bVok=";
    };
    date = "2025-02-23";
  };
  wildplus-kernel-patches = {
    pname = "wildplus-kernel-patches";
    version = "ebf90e499eb87d42a70cc17b431a03f2c650ca71";
    src = fetchFromGitHub {
      owner = "WildPlusKernel";
      repo = "kernel_patches";
      rev = "ebf90e499eb87d42a70cc17b431a03f2c650ca71";
      fetchSubmodules = false;
      sha256 = "sha256-TKyabYIjmZs4GcWpkMV1u2FOL8ecR+IEjk+vCmRYHAg=";
    };
    date = "2025-03-09";
  };
  ztc1997-android_gki_kernel_5-10_common = {
    pname = "ztc1997-android_gki_kernel_5-10_common";
    version = "e13b3ac615cf019c36fa0d1f0b1f2e14ba3885ce";
    src = fetchFromGitHub {
      owner = "ztc1997";
      repo = "android_gki_kernel_5.10_common";
      rev = "e13b3ac615cf019c36fa0d1f0b1f2e14ba3885ce";
      fetchSubmodules = false;
      sha256 = "sha256-tZWaP+q8p7gCHBbZdcdzqIGT051eoTnR3gPWzGlp7+c=";
    };
    date = "2025-01-21";
  };
  ztc1997-android_gki_kernel_5-15_common = {
    pname = "ztc1997-android_gki_kernel_5-15_common";
    version = "0615c0e0cab9d7b1f5c24c7687f23c9d5bac0117";
    src = fetchFromGitHub {
      owner = "ztc1997";
      repo = "android_gki_kernel_5.15_common";
      rev = "0615c0e0cab9d7b1f5c24c7687f23c9d5bac0117";
      fetchSubmodules = false;
      sha256 = "sha256-uJNVK/kJgWCBUxHurKAedokKz2WtYaZ17Ib0yp7N9WI=";
    };
    date = "2024-09-03";
  };
}
