# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  AAAAA_android_kernel_samsung_lykanlte = {
    pname = "AAAAA_android_kernel_samsung_lykanlte";
    version = "c7e14de69d0124bf1827325aba013ec7b25e5bcb";
    src = fetchFromGitHub {
      owner = "DataEraserC";
      repo = "android_kernel_samsung_lykanlte";
      rev = "c7e14de69d0124bf1827325aba013ec7b25e5bcb";
      fetchSubmodules = true;
      sha256 = "sha256-AP9m+TwFJXQ1AusKl6ZuNK9Jv+D5B/akaZ/6La3Z+t8=";
    };
    date = "2025-03-17";
  };
  AAAAA_android_kernel_samsung_sm8250_TabS7 = {
    pname = "AAAAA_android_kernel_samsung_sm8250_TabS7";
    version = "a06a3c6904d3a7c7fd4d09769d18a44053fcca7e";
    src = fetchFromGitHub {
      owner = "DataEraserC";
      repo = "android_kernel_samsung_sm8250_TabS7";
      rev = "a06a3c6904d3a7c7fd4d09769d18a44053fcca7e";
      fetchSubmodules = true;
      sha256 = "sha256-dHwai7E/e4Y/V4SnGwNJchRjkbS01IKuDZQmiT9ifyI=";
    };
    date = "2025-03-15";
  };
  AAAAA_android_prebuilts_clang_kernel_linux-x86_clang-r416183b = {
    pname = "AAAAA_android_prebuilts_clang_kernel_linux-x86_clang-r416183b";
    version = "54220fd601050b350b2af7adc913089ebf0e7aed";
    src = fetchFromGitHub {
      owner = "LineageOS";
      repo = "android_prebuilts_clang_kernel_linux-x86_clang-r416183b";
      rev = "54220fd601050b350b2af7adc913089ebf0e7aed";
      fetchSubmodules = false;
      sha256 = "sha256-o9e5VRR6s2T9NDwDY8XuG2GYUKbZQF1s687gPlE0+RY=";
    };
    date = "2022-11-01";
  };
  AAAAA_kernelsu-rksu = {
    pname = "AAAAA_kernelsu-rksu";
    version = "v3.0.0-30-legacy";
    src = fetchgit {
      url = "https://github.com/rsuntk/KernelSU.git";
      rev = "v3.0.0-30-legacy";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-+w7uaEBq4KACxSyOZ3AFEGMMx71t6EF1gRtXJJLNBqU=";
    };
  };
  AAAAA_kernelsu-rksu-susfs = {
    pname = "AAAAA_kernelsu-rksu-susfs";
    version = "9b28326af4145974560122644e87fc9a021a2cce";
    src = fetchFromGitHub {
      owner = "rsuntk";
      repo = "KernelSU";
      rev = "9b28326af4145974560122644e87fc9a021a2cce";
      fetchSubmodules = false;
      sha256 = "sha256-3F1gtCBNq0cLOJeyUugku6vAbRczS3VyEhDEWcfi9l8=";
    };
    date = "2025-12-20";
  };
  AAAAA_lineage-nightly-pstar_bootImg = {
    pname = "AAAAA_lineage-nightly-pstar_bootImg";
    version = "20260216";
    src = fetchurl {
      url = "https://mirrorbits.lineageos.org/full/pstar/20260216/boot.img";
      sha256 = "sha256-qzAw/w2pSWa7k5b4Qp3T0EHKHSSoXZI4OHVOJlTQvG8=";
    };
  };
  AAAAA_linux-moto-pstar-lineageos-22_1 = {
    pname = "AAAAA_linux-moto-pstar-lineageos-22_1";
    version = "8a06559e98bb6685033d8771865bac00e9618cce";
    src = fetchFromGitHub {
      owner = "AndroidAppsUsedByMyself";
      repo = "android_kernel_motorola_sm8250";
      rev = "8a06559e98bb6685033d8771865bac00e9618cce";
      fetchSubmodules = false;
      sha256 = "sha256-yrjP65l1U5DwEdhyuu1AsJdfa78qXaqHqt53gBOvWEQ=";
    };
    date = "2025-03-15";
  };
  AAAAA_linux-xiaomi-gauguin-lineageos-22_1 = {
    pname = "AAAAA_linux-xiaomi-gauguin-lineageos-22_1";
    version = "8d52ff9a898e05001383345eb882a488be38f59a";
    src = fetchFromGitHub {
      owner = "LineageOS";
      repo = "android_kernel_xiaomi_gauguin";
      rev = "8d52ff9a898e05001383345eb882a488be38f59a";
      fetchSubmodules = false;
      sha256 = "sha256-/6K3MBk7R/YCgKq7aW0vxxcn0pDMETZOjHx20XvA/ig=";
    };
    date = "2025-04-02";
  };
  AAAAA_llvm-arm-toolchain-ship-10_0 = {
    pname = "AAAAA_llvm-arm-toolchain-ship-10_0";
    version = "c6aaf7026bd49a06e12ec0551285ffded148d186";
    src = fetchFromGitHub {
      owner = "proprietary-stuff";
      repo = "llvm-arm-toolchain-ship-10.0";
      rev = "c6aaf7026bd49a06e12ec0551285ffded148d186";
      fetchSubmodules = false;
      sha256 = "sha256-PwJj4yZv/FotEncyw5nZmw5upUz7gx35TdDCVkb0+xU=";
    };
    date = "2020-09-27";
  };
  AAAAA_los-pstar-kernel-patches = {
    pname = "AAAAA_los-pstar-kernel-patches";
    version = "9ae66533892ed7bb8262cf4a49fa986e14c3e0f8";
    src = fetchFromGitHub {
      owner = "AndroidAppsUsedByMyself";
      repo = "kernel_patches";
      rev = "9ae66533892ed7bb8262cf4a49fa986e14c3e0f8";
      fetchSubmodules = false;
      sha256 = "sha256-lDor+o7BKpYeWI16oX+I0Etwgi0bv0n2HuPWiGjChQA=";
    };
    date = "2025-04-11";
  };
  AAAAA_susfs-4_19 = {
    pname = "AAAAA_susfs-4_19";
    version = "001e69919c6271f690fd00b17e4c721c9e599152";
    src = fetchgit {
      url = "https://gitlab.com/simonpunk/susfs4ksu.git";
      rev = "001e69919c6271f690fd00b17e4c721c9e599152";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-j4OIvgOE64nm67NyGsEnSRNygVVZaF5uhMx8ju+p6fQ=";
    };
    date = "2025-02-23";
  };
  AAAAA_ztc1997-android_gki_kernel_5-10_common = {
    pname = "AAAAA_ztc1997-android_gki_kernel_5-10_common";
    version = "e13b3ac615cf019c36fa0d1f0b1f2e14ba3885ce";
    src = fetchFromGitHub {
      owner = "ztc1997";
      repo = "android_gki_kernel_5.10_common";
      rev = "e13b3ac615cf019c36fa0d1f0b1f2e14ba3885ce";
      fetchSubmodules = false;
      sha256 = "sha256-tZWaP+q8p7gCHBbZdcdzqIGT051eoTnR3gPWzGlp7+c=";
    };
    date = "2025-01-21";
  };
  AAAAA_ztc1997-android_gki_kernel_5-15_common = {
    pname = "AAAAA_ztc1997-android_gki_kernel_5-15_common";
    version = "0615c0e0cab9d7b1f5c24c7687f23c9d5bac0117";
    src = fetchFromGitHub {
      owner = "ztc1997";
      repo = "android_gki_kernel_5.15_common";
      rev = "0615c0e0cab9d7b1f5c24c7687f23c9d5bac0117";
      fetchSubmodules = false;
      sha256 = "sha256-uJNVK/kJgWCBUxHurKAedokKz2WtYaZ17Ib0yp7N9WI=";
    };
    date = "2024-09-03";
  };
  anykernel-kernelsu = {
    pname = "anykernel-kernelsu";
    version = "80e0cc9e736572ad16c7dc539ba9b6e40749f8e7";
    src = fetchFromGitHub {
      owner = "Kernel-SU";
      repo = "AnyKernel3";
      rev = "80e0cc9e736572ad16c7dc539ba9b6e40749f8e7";
      fetchSubmodules = false;
      sha256 = "sha256-8zVOkoMXkKQ+SCBg7jYn2H+RP7bb9x8MAOy/8d/P6Cc=";
    };
    date = "2025-11-07";
  };
  anykernel-osm0sis = {
    pname = "anykernel-osm0sis";
    version = "63c886e3b379d74c4fc0412b78896132b0702881";
    src = fetchFromGitHub {
      owner = "osm0sis";
      repo = "AnyKernel3";
      rev = "63c886e3b379d74c4fc0412b78896132b0702881";
      fetchSubmodules = false;
      sha256 = "sha256-NLZG2beOls6qNE2+tbrpZ6pF4JYATP2U+0xfpMhOhhI=";
    };
    date = "2026-02-08";
  };
  baseband-guard = {
    pname = "baseband-guard";
    version = "886bc0c86be197a1f4d44b8edf895b549bc0e908";
    src = fetchFromGitHub {
      owner = "vc-teahouse";
      repo = "Baseband-guard";
      rev = "886bc0c86be197a1f4d44b8edf895b549bc0e908";
      fetchSubmodules = false;
      sha256 = "sha256-KrS0idcAHbciUPn8CQhlWQ4sYIyYxqzMcSGX+FYpFdg=";
    };
    date = "2026-02-07";
  };
  gcc-aarch64-linux-android = {
    pname = "gcc-aarch64-linux-android";
    version = "5797d7f622321e734558bd3372a9ab5ad6e6a48e";
    src = fetchFromGitHub {
      owner = "kindle4jerry";
      repo = "aarch64-linux-android-4.9-bakup";
      rev = "5797d7f622321e734558bd3372a9ab5ad6e6a48e";
      fetchSubmodules = false;
      sha256 = "sha256-ZrQmFyiDOKg+qcgdpZqtz+LgDDaao2W27kdZZ2As8XU=";
    };
    date = "2020-02-22";
  };
  gcc-arm-linux-androideabi = {
    pname = "gcc-arm-linux-androideabi";
    version = "3ecb542702c2ca0e502533c3f6d02f0f06f584f1";
    src = fetchFromGitHub {
      owner = "KudProject";
      repo = "arm-linux-androideabi-4.9";
      rev = "3ecb542702c2ca0e502533c3f6d02f0f06f584f1";
      fetchSubmodules = false;
      sha256 = "sha256-5aF2Pl+h6J8/5TfQf2ojp3FCnoKakWH6KBCkWdy5ho8=";
    };
    date = "2019-11-25";
  };
  kernelsu-next = {
    pname = "kernelsu-next";
    version = "v3.0.1";
    src = fetchgit {
      url = "https://github.com/rifsxd/KernelSU-Next.git";
      rev = "v3.0.1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-1XS7auSOiIT8O3Aa+tGW8eQoCyAoaLgSCIxutuXKBgs=";
    };
  };
  kernelsu-stable = {
    pname = "kernelsu-stable";
    version = "v0.9.5";
    src = fetchgit {
      url = "https://github.com/tiann/KernelSU.git";
      rev = "v0.9.5";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-pvaL6KEB7X3s8zyLQSPhBhoXaNdVDthH7HnAZRE9JYk=";
    };
  };
  linux-amazon-karnak = {
    pname = "linux-amazon-karnak";
    version = "e22c713c7c4f0c8d08267f6bba98b8c4cde8310f";
    src = fetchFromGitHub {
      owner = "mt8163";
      repo = "android_kernel_amazon_karnak_4.9";
      rev = "e22c713c7c4f0c8d08267f6bba98b8c4cde8310f";
      fetchSubmodules = false;
      sha256 = "sha256-viqlQBPd2SuiAphFKiwjtckC3gDTGkbLv2dgZKMP3Oc=";
    };
    date = "2023-10-09";
  };
  linux-moto-rtwo-lineageos-21 = {
    pname = "linux-moto-rtwo-lineageos-21";
    version = "1bdeb4f5c8d2b98ef5f2bedaa5d704032dffd676";
    src = fetchFromGitHub {
      owner = "LineageOS";
      repo = "android_kernel_motorola_sm8550";
      rev = "1bdeb4f5c8d2b98ef5f2bedaa5d704032dffd676";
      fetchSubmodules = false;
      sha256 = "sha256-ZK/DH5N5LdkLe48cANESjw1x74aXoZLFoMAwEDvzEk4=";
    };
    date = "2024-12-21";
  };
  linux-moto-rtwo-lineageos-22_1 = {
    pname = "linux-moto-rtwo-lineageos-22_1";
    version = "e12cc3a36c10596aced0e84a0e08072161c45f63";
    src = fetchFromGitHub {
      owner = "LineageOS";
      repo = "android_kernel_motorola_sm8550";
      rev = "e12cc3a36c10596aced0e84a0e08072161c45f63";
      fetchSubmodules = false;
      sha256 = "sha256-KZSIus0Ws7FM4O9zyxmdPvGcYsXv/rubwnOuwgo7yHw=";
    };
    date = "2025-03-28";
  };
  linux-oneplus-13 = {
    pname = "linux-oneplus-13";
    version = "9920459dfb0080dd8a81c41d95701483857f804a";
    src = fetchFromGitHub {
      owner = "OnePlusOSS";
      repo = "android_kernel_common_oneplus_sm8750";
      rev = "9920459dfb0080dd8a81c41d95701483857f804a";
      fetchSubmodules = false;
      sha256 = "sha256-EDX16/0QWSdC70sAyuNFTdQ9sNreXdvJRAmZvBLsXq8=";
    };
    date = "2025-08-30";
  };
  linux-oneplus-8t-blu-spark = {
    pname = "linux-oneplus-8t-blu-spark";
    version = "64c109e3f3ba97fa7aed730ab7b4238b91df028b";
    src = fetchFromGitHub {
      owner = "engstk";
      repo = "op8";
      rev = "64c109e3f3ba97fa7aed730ab7b4238b91df028b";
      fetchSubmodules = false;
      sha256 = "sha256-KWLtY7KWhHmk6LVYpvIz6XT93+yjteex/250crk9Lxw=";
    };
    date = "2024-12-26";
  };
  oneplus-13-sched-ext = {
    pname = "oneplus-13-sched-ext";
    version = "7ab1d04d5cb622d6c32c932add617803074ec5a7";
    src = fetchFromGitHub {
      owner = "HanKuCha";
      repo = "sched_ext";
      rev = "7ab1d04d5cb622d6c32c932add617803074ec5a7";
      fetchSubmodules = false;
      sha256 = "sha256-GamqRqQDjssYudTAfpwXuVbdEZfwWVOLBipagn9WkHw=";
    };
    date = "2025-06-14";
  };
  sukisu = {
    pname = "sukisu";
    version = "178d01cf996b8b38675f7a603afb4dba3267f588";
    src = fetchFromGitHub {
      owner = "SukiSU-Ultra";
      repo = "SukiSU-Ultra";
      rev = "178d01cf996b8b38675f7a603afb4dba3267f588";
      fetchSubmodules = false;
      sha256 = "sha256-30tn0s1UNUJT85qN6ok2Tqst75A0AFWn+ZSt48Nt9H4=";
    };
    date = "2026-02-10";
  };
  sukisu-nongki = {
    pname = "sukisu-nongki";
    version = "178d01cf996b8b38675f7a603afb4dba3267f588";
    src = fetchFromGitHub {
      owner = "SukiSU-Ultra";
      repo = "SukiSU-Ultra";
      rev = "178d01cf996b8b38675f7a603afb4dba3267f588";
      fetchSubmodules = false;
      sha256 = "sha256-30tn0s1UNUJT85qN6ok2Tqst75A0AFWn+ZSt48Nt9H4=";
    };
    date = "2026-02-10";
  };
  sukisu-patch = {
    pname = "sukisu-patch";
    version = "4e61456f26da6ffdab6d2bc68baa4ad66e242695";
    src = fetchFromGitHub {
      owner = "SukiSU-Ultra";
      repo = "SukiSU_patch";
      rev = "4e61456f26da6ffdab6d2bc68baa4ad66e242695";
      fetchSubmodules = false;
      sha256 = "sha256-ArRH2JkS/RGA5bMPWtfeczOATTGp/R4+Rs3du3dpf0o=";
    };
    date = "2026-01-30";
  };
  sukisu-susfs = {
    pname = "sukisu-susfs";
    version = "178d01cf996b8b38675f7a603afb4dba3267f588";
    src = fetchFromGitHub {
      owner = "SukiSU-Ultra";
      repo = "SukiSU-Ultra";
      rev = "178d01cf996b8b38675f7a603afb4dba3267f588";
      fetchSubmodules = false;
      sha256 = "sha256-30tn0s1UNUJT85qN6ok2Tqst75A0AFWn+ZSt48Nt9H4=";
    };
    date = "2026-02-10";
  };
  susfs-android13-5_15 = {
    pname = "susfs-android13-5_15";
    version = "d8da61b4d27c39803b6ee472ccab1fbe74e4f5ba";
    src = fetchgit {
      url = "https://gitlab.com/simonpunk/susfs4ksu.git";
      rev = "d8da61b4d27c39803b6ee472ccab1fbe74e4f5ba";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-1Tx29afz/P32oEq8Lk/dnyxmkq8j1Pxzza2PmxY9YXo=";
    };
    date = "2026-02-15";
  };
  susfs-android15-6_6 = {
    pname = "susfs-android15-6_6";
    version = "92783393fdca3c506e66765fde6a5aeff136a473";
    src = fetchgit {
      url = "https://gitlab.com/simonpunk/susfs4ksu.git";
      rev = "92783393fdca3c506e66765fde6a5aeff136a473";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-TswYN7pQGKV+8eHSNbC4M4UHBAE+uzjva6Pd2yEFkx4=";
    };
    date = "2026-02-15";
  };
  wildplus-kernel-patches = {
    pname = "wildplus-kernel-patches";
    version = "9bf80a4b58ddfafc1a94e73ac923bc87a622efb2";
    src = fetchFromGitHub {
      owner = "WildPlusKernel";
      repo = "kernel_patches";
      rev = "9bf80a4b58ddfafc1a94e73ac923bc87a622efb2";
      fetchSubmodules = false;
      sha256 = "sha256-99g7dUfGXf5Fb0oie4zT8aAYd3Nm+0MCtlMdxNOfjYw=";
    };
    date = "2026-02-11";
  };
}
