# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  android_prebuilts_clang_kernel_linux-x86_clang-r416183b = {
    pname = "android_prebuilts_clang_kernel_linux-x86_clang-r416183b";
    version = "54220fd601050b350b2af7adc913089ebf0e7aed";
    src = fetchFromGitHub {
      owner = "LineageOS";
      repo = "android_prebuilts_clang_kernel_linux-x86_clang-r416183b";
      rev = "54220fd601050b350b2af7adc913089ebf0e7aed";
      fetchSubmodules = false;
      sha256 = "sha256-o9e5VRR6s2T9NDwDY8XuG2GYUKbZQF1s687gPlE0+RY=";
    };
    date = "2022-11-01";
  };
  anykernel-kernelsu = {
    pname = "anykernel-kernelsu";
    version = "ee30bad85a483cad2b1e4ff34e69f983a04f875a";
    src = fetchFromGitHub {
      owner = "Kernel-SU";
      repo = "AnyKernel3";
      rev = "ee30bad85a483cad2b1e4ff34e69f983a04f875a";
      fetchSubmodules = false;
      sha256 = "sha256-QJS4+1teNcgUOy2gD+KuoEG/9pUNd/6uSH84AkAlVoQ=";
    };
    date = "2023-10-30";
  };
  anykernel-osm0sis = {
    pname = "anykernel-osm0sis";
    version = "db90e19aae369c9c10b956a08003cee3958d50a0";
    src = fetchFromGitHub {
      owner = "osm0sis";
      repo = "AnyKernel3";
      rev = "db90e19aae369c9c10b956a08003cee3958d50a0";
      fetchSubmodules = false;
      sha256 = "sha256-MofvAxGUB4kcOmm42u3rDFPR7Pj63OjaC4FRP9jAy0k=";
    };
    date = "2024-12-17";
  };
  gcc-aarch64-linux-android = {
    pname = "gcc-aarch64-linux-android";
    version = "5797d7f622321e734558bd3372a9ab5ad6e6a48e";
    src = fetchFromGitHub {
      owner = "kindle4jerry";
      repo = "aarch64-linux-android-4.9-bakup";
      rev = "5797d7f622321e734558bd3372a9ab5ad6e6a48e";
      fetchSubmodules = false;
      sha256 = "sha256-ZrQmFyiDOKg+qcgdpZqtz+LgDDaao2W27kdZZ2As8XU=";
    };
    date = "2020-02-22";
  };
  gcc-arm-linux-androideabi = {
    pname = "gcc-arm-linux-androideabi";
    version = "3ecb542702c2ca0e502533c3f6d02f0f06f584f1";
    src = fetchFromGitHub {
      owner = "KudProject";
      repo = "arm-linux-androideabi-4.9";
      rev = "3ecb542702c2ca0e502533c3f6d02f0f06f584f1";
      fetchSubmodules = false;
      sha256 = "sha256-5aF2Pl+h6J8/5TfQf2ojp3FCnoKakWH6KBCkWdy5ho8=";
    };
    date = "2019-11-25";
  };
  kernelsu-stable = {
    pname = "kernelsu-stable";
    version = "v0.9.5";
    src = fetchgit {
      url = "https://github.com/tiann/KernelSU.git";
      rev = "v0.9.5";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-pvaL6KEB7X3s8zyLQSPhBhoXaNdVDthH7HnAZRE9JYk=";
    };
  };
  kernelsu-stable-revision-code = {
    pname = "kernelsu-stable-revision-code";
    version = "11872";
    src = fetchurl {
      url = "https://example.com";
      sha256 = "sha256-6o+sfGX7WJsNU1YPUlH3T56bJDR43Laz6nm142RJyNk=";
    };
  };
  lineage-nightly-pstar_bootImg = {
    pname = "lineage-nightly-pstar_bootImg";
    version = "20241223";
    src = fetchurl {
      url = "https://mirrorbits.lineageos.org/full/pstar/20241223/boot.img";
      sha256 = "sha256-kk3B4O11CPFa3+8Mu+4uZKsPn+4AmgwyWIQbAhy8bb0=";
    };
  };
  linux-amazon-karnak = {
    pname = "linux-amazon-karnak";
    version = "e22c713c7c4f0c8d08267f6bba98b8c4cde8310f";
    src = fetchFromGitHub {
      owner = "mt8163";
      repo = "android_kernel_amazon_karnak_4.9";
      rev = "e22c713c7c4f0c8d08267f6bba98b8c4cde8310f";
      fetchSubmodules = false;
      sha256 = "sha256-viqlQBPd2SuiAphFKiwjtckC3gDTGkbLv2dgZKMP3Oc=";
    };
    date = "2023-10-09";
  };
  linux-moto-pstar-lineageos-22_0 = {
    pname = "linux-moto-pstar-lineageos-22_0";
    version = "8a3a7fa629d0846adc83f42b6d880e717e4f9783";
    src = fetchFromGitHub {
      owner = "AndroidAppsUsedByMyself";
      repo = "android_kernel_motorola_sm8250";
      rev = "8a3a7fa629d0846adc83f42b6d880e717e4f9783";
      fetchSubmodules = false;
      sha256 = "sha256-eCTtAcJibh5OYhEdzgApnAce7ZBuCqcS4PD3eh9dUZk=";
    };
    date = "2024-12-21";
  };
  linux-moto-rtwo-lineageos-21 = {
    pname = "linux-moto-rtwo-lineageos-21";
    version = "1c2aa53515b7c1d5629a84980470d9c1c2ece4e7";
    src = fetchFromGitHub {
      owner = "moto-sm8550";
      repo = "android_kernel_motorola_sm8550";
      rev = "1c2aa53515b7c1d5629a84980470d9c1c2ece4e7";
      fetchSubmodules = false;
      sha256 = "sha256-1czfscSPxDELAfyeNmrFG0x2GfCOl8CHe2C7GOsfR40=";
    };
    date = "2024-02-23";
  };
  linux-oneplus-8t-blu-spark = {
    pname = "linux-oneplus-8t-blu-spark";
    version = "2248fcf83d2a19ac0adb12bc6ed319b31090f6f4";
    src = fetchFromGitHub {
      owner = "engstk";
      repo = "op8";
      rev = "2248fcf83d2a19ac0adb12bc6ed319b31090f6f4";
      fetchSubmodules = false;
      sha256 = "sha256-ofzdtkWRcPiXWvzoonv654lyDM7NsWdBE8m1JxmnGMk=";
    };
    date = "2024-11-14";
  };
  ztc1997-android_gki_kernel_5-10_common = {
    pname = "ztc1997-android_gki_kernel_5-10_common";
    version = "c9a80e00191ed9d05f6b5492b54a55a8afe87c87";
    src = fetchFromGitHub {
      owner = "ztc1997";
      repo = "android_gki_kernel_5.10_common";
      rev = "c9a80e00191ed9d05f6b5492b54a55a8afe87c87";
      fetchSubmodules = false;
      sha256 = "sha256-r8XRHNpIsqVFTgzdycRpAEaE3L5n+8ohurqGX9/+gSw=";
    };
    date = "2024-12-18";
  };
  ztc1997-android_gki_kernel_5-15_common = {
    pname = "ztc1997-android_gki_kernel_5-15_common";
    version = "0615c0e0cab9d7b1f5c24c7687f23c9d5bac0117";
    src = fetchFromGitHub {
      owner = "ztc1997";
      repo = "android_gki_kernel_5.15_common";
      rev = "0615c0e0cab9d7b1f5c24c7687f23c9d5bac0117";
      fetchSubmodules = false;
      sha256 = "sha256-uJNVK/kJgWCBUxHurKAedokKz2WtYaZ17Ib0yp7N9WI=";
    };
    date = "2024-09-03";
  };
}
